# docker-compose.yml
version: '3'
services: 
    database:
        container_name: ctk-ws-db
        image: postgres:13.2-alpine
        env_file:
            - database.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
        db-data: 